# Generated by Django 3.2.25 on 2024-03-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rated_user',
            new_name='rate_user',
        ),
    ]
