# Generated by Django 3.2.25 on 2024-03-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
