# Generated by Django 3.2.25 on 2024-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('employer', 'Employer'), ('admin', 'Admin')], default='', max_length=10),
        ),
    ]
