# Generated by Django 3.2.25 on 2024-03-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
