# Generated by Django 4.2.11 on 2024-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_signupcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_signup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SignupCompletion',
        ),
    ]
