# Generated by Django 3.2.25 on 2024-03-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_alter_profile_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_responded', models.BooleanField(default=False)),
                ('employee_acceptance_response', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('employee_status', models.CharField(choices=[('applied', 'Applied')], default='applied', max_length=20)),
                ('employer_applicant_choice', models.CharField(choices=[('binned', 'Binned'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('applicant', models.ForeignKey(limit_choices_to={'profile_type': 'employee'}, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('closing_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positions_available', models.PositiveIntegerField(default=1, help_text='Number of positions available')),
                ('is_listing_closed', models.BooleanField(default=False)),
                ('applicants', models.ManyToManyField(blank=True, related_name='job_applications', through='jobs.Application', to='profiles.Profile')),
                ('employees', models.ManyToManyField(blank=True, limit_choices_to={'profile_type': 'employee'}, related_name='assigned_jobs', to='profiles.Profile')),
                ('employer_profile', models.ForeignKey(limit_choices_to={'profile_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_created', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
