# Generated by Django 3.2.25 on 2024-03-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_type'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='binned_applicants',
            field=models.ManyToManyField(blank=True, related_name='binned_jobs', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_listing_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='shortlisted_applicants',
            field=models.ManyToManyField(blank=True, related_name='shortlisted_jobs', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied')], default='pending', max_length=20),
        ),
    ]
