# Generated by Django 3.2.25 on 2024-03-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_type'),
        ('jobs', '0002_auto_20240312_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='binned_applicants',
        ),
        migrations.RemoveField(
            model_name='job',
            name='shortlisted_applicants',
        ),
        migrations.CreateModel(
            name='JobOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_applicants', models.ManyToManyField(blank=True, related_name='accepted_jobs', to='profiles.Profile')),
                ('binned_applicants', models.ManyToManyField(blank=True, related_name='binned_jobs', to='profiles.Profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('shortlisted_applicants', models.ManyToManyField(blank=True, related_name='shortlisted_jobs', to='profiles.Profile')),
            ],
            options={
                'verbose_name_plural': 'Job Outcomes',
            },
        ),
    ]
