# Generated by Django 3.2.25 on 2024-03-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20240312_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='employee_status',
            field=models.CharField(choices=[('applied', 'Applied')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_applicant_status',
            field=models.CharField(choices=[('binned', 'Binned'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted')], default='applied', max_length=20),
        ),
        migrations.DeleteModel(
            name='JobOutcome',
        ),
    ]
