# Generated by Django 3.2.25 on 2024-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20240312_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='employer_applicant_status',
        ),
        migrations.AddField(
            model_name='application',
            name='employer_applicant_choice',
            field=models.CharField(choices=[('binned', 'Binned'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
