# Generated by Django 3.2.25 on 2024-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_type'),
        ('jobs', '0005_auto_20240312_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile_type': 'employee'}, related_name='assigned_jobs', to='profiles.Profile'),
        ),
    ]
