# Generated by Django 3.2.25 on 2024-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employee_acceptance_response',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
