# Generated by Django 3.2.25 on 2024-03-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_employee_acceptance_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
    ]
