# Generated by Django 3.2.25 on 2024-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
