# Generated by Django 3.2.25 on 2024-03-18 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_alter_message_recipient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('sender', 'recipient', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('chat', 'sender', 'recipient', 'timestamp')},
        ),
    ]
