# Generated by Django 3.2.25 on 2024-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
